image: node:10

cache:
    paths:
        - node_modules/

stages:
    - install
    - test
    - build

.test_template: &test_template
    stage: test
    except:
        - triggers
        - tags
        - schedules
    variables:
        NODE_ENV: 'testing'
        BABEL_ENV: 'test'

lint:
    <<: *test_template
    script:
        - npm run lint

node_modules:
    stage: install
    script:
        - npm install
        - npm version
    artifacts:
        paths:
            - node_modules
    except:
        - triggers
        - tags

build_image:
    stage: build
    only: 
        - master
        - stable
        - development
        - /^release-.*$/
    image: docker:git # use simply git docker image
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
        - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
        - docker push registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
